### PR TITLE
Bumped libbuildpack-dynatrace to 1.4.1

### PR DESCRIPTION
**Pull request by arthfl**
* A short explanation of the proposed change:
Bumped  libbuildpack-dynatrace to 1.4.1 to include the networkzone parameter when downloading the OneAgent from the API
* An explanation of the use cases your change solves
This includes the networkzone parameter when downloading the OneAgent from the API
* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

### CODE REVIEW

**Comment by arthfl** [comment]
Dear maintainers, any ETA on this?

**Comment by brayanhenao** [comment]
Hi @arthfl, apologies for such a long response time to this issue.

The version bump of `libbuildpack-dynatrace` from `1.4.1` to `1.4.2` was handled by our [Dependabot](https://github.com/cloudfoundry/python-buildpack/commit/b6789d4128e67c65b032e4f48f601e0e406007cf). Right now these changes remain in develop branch and will be included in the next release of the Python Buildpack (1.7.48) which will be available by the end of this week at the latest.

I will close the issue.

**Comment by brayanhenao** [comment]
@arthfl [`Python Buildpack v1.7.48`](https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.48) released with `libbuildpack-dynatrace v1.4.2`

**Comment by arthfl** [comment]
No worries. Thanks a lot :-)

**Pull request closed without merging**
