### PR TITLE
bumped libbuildpack-dynatrace to v1.5.0

### PR DESCRIPTION
**Pull request by arthfl**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
bumped libbuildpack-dynatrace to v1.5.0
updated fake dynatrace api and integration test to take care of the OneAgent config update functionality

* An explanation of the use cases your change solves
Usage of libbuildpack-dyntrace v1.5.0 enables OneAgent config updating during app deployment

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

### CODE REVIEW

**Comment by arthfl** [comment]
@brayanhenao I'd really like to run the integration tests locally, but the whole suite of scripts is based on a very outdated version of Ruby `Your Ruby version is 3.0.4, but your Gemfile specified ~> 2.3` for which officiall support was ended in 2019 (https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/)

If you folks can update that to something more recent which is available and supported currently, i'll happily re-test everything :-)

**Comment by brayanhenao** [comment]
@arthfl You don't even need to have ruby to run integration tests. You just need:

* Go
* jq
* cf cli (with credentials and permissions as indicated in the guide to run the integration tests)

We recommend that when running the tests you focus the Dynatrace suite putting an `F` at the beginning of the `Describe` 
 command as follows:

```go
var _ = FDescribe("CF Python Buildpack", func() {
        var (
                app             *cutlass.App
                createdServices []string
                dynatraceAPI    *cutlass.App
                dynatraceAPIURI string
        )
```

**Comment by arthfl** [comment]
@brayanhenao 
Ok, how?

Because when i do it like the documentation describes (which you also linked) i get:
```bash
$ source .envrc 
$ ./scripts/integration.sh 
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/lib/ruby/gems/3.0.0
  /usr/lib/ruby/gems/3.0.0/build_info
  /usr/lib/ruby/gems/3.0.0/cache
  /usr/lib/ruby/gems/3.0.0/doc
  /usr/lib/ruby/gems/3.0.0/extensions
  /usr/lib/ruby/gems/3.0.0/gems
  /usr/lib/ruby/gems/3.0.0/plugins
  /usr/lib/ruby/gems/3.0.0/specifications
Your Ruby version is 3.0.4, but your Gemfile specified ~> 2.3
```
...i'd argue that Ruby is somewhat involved here.
So please update the documentation here and tell me how you run the integration tests without Ruby being involved :-)

**Comment by brayanhenao** [comment]
Realy weird interaction, we will investigate the error running the tests. I ran these tests inside a docker image that I create (`docker run -it bhenao/ubuntu bash`) based on Ubuntu 22.04 with some additional packages (It doesn't even contain ruby) and it works.

Also, locally, I have Ruby `3.x` version installed and it also works fine.

```bash
❯ ruby -v
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-darwin21]
```

To make the process a little easier, I'm going to paste the error log of one test (all of them fail for the same reason):

Error: 
```
ERR /tmp/paasInstaller.sh: line 15: /tmp/app/dynatrace/oneagent/agent/conf/ruxitagentproc.conf: No such file or directory
```

Full log:
[log1.txt](https://github.com/cloudfoundry/python-buildpack/files/8922024/log1.txt)

**Comment by arthfl** [comment]
@brayanhenao
This should fix the no such file or directory errors

**Pull request merged**
