### PR TITLE
Add Graphviz support

### PR DESCRIPTION
**Pull request by kdunn-pivotal**
* Certain Python libraries depend on Graphviz libraries and binaries in the runtime environment, I've templated off of similar binary package dependencies in this build pack to accommodate that requirement.

* I've already deployed a webapp utilizing this functionality, so it has therefor been tested. [Simple PyGrapviz Webapp](http://explainvizpy.cfapps.io)

* I am covered under a Corporate CLA

### CODE REVIEW

**Comment by sesmith177** [comment]
Hello @kdunn-pivotal,

We don't think that the python buildpack is the proper location to add generic library support. We would like to note that the graphviz libraries are already in the "stack" and thus available to use, what is missing is the graphviz executables.

As a workaround, you could:

1. Fork the buildpack and add you change. At this point, it would be necessary to regularly pull in upstream changes for security reasons (at the very least)
1. Download the graphiz executables into a directory of your application (e.g. `./bin/`). Then, in your Procfile, add this directory to the PATH, e.g.
`web: PATH=$PWD/bin:$PATH python explainViz.py`

**Comment by flavorjones** [comment]
Have we considered adding the `graphviz` package to the rootfs? If so, can you help me and the original poster understand why that idea was rejected?

**Comment by Dannyzen** [comment]
As this was the first request for graphviz we opted to not include it in the rootfs, however if there's a significant community interest in its inclusion it would be something to reconsider. I'd like to move forward and request if the community finds value in adding this package to the rootfs.

**Comment by Dannyzen** [comment]
As an update, there was no expressed community interest in including graphviz in the rootfs and we have closed the requesting issue https://github.com/cloudfoundry/stacks/issues/33

**Pull request closed without merging**
